pipeline {
    agent any

    environment {
        SERVICE_NAME = "path-planner"
        REGISTRY = "docker.io/bhavesh"
        IMAGE_TAG = "${GIT_COMMIT}"
        MANIFEST_REPO = "git@github.com:bhavesh07-ms/greenpath-manifests.git"
        ENV = "dev"
    }

    stages {

        stage("Checkout Source") {
            steps {
                checkout scm
            }
        }
        stage("Build commonutils") {
                      steps {
                          dir("commonutils") {
                              sh "mvn clean install"
                          }
                  }
            }

        stage("Build & Test") {
    steps {
        dir("server/path-planner-service") {
            sh "mvn clean package"
        }
    }
}

stage("Build Docker Image") {
    steps {
        dir("server/path-planner-service") {
            sh """
            docker build -t ${REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG} .
            """
        }
    }
}


        stage("Push Docker Image") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push ${REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage("Deploy to ECS") {
            steps {
                sh """
                aws ecs update-service \
                  --cluster greenpath-cluster \
                  --service path-planner-service \
                  --force-new-deployment
                """
            }
        }
    }
}
